apiVersion: v1
kind: Service
metadata:
  name: netflix-clone
spec:
  ports:
  - port: 31008
    nodePort: 31012
    targetPort: 80
    protocol: TCP
  selector:
    app: netflix-clone
  type: NodePort
  
